- hosts: '*_role_splunk'
  gather_facts: False
  collections:
    - splunk.es
  vars:
    ansible_network_os: splunk.es.splunk
    ansible_user: "{{ splunk_common_admin_user }}"
    ansible_httpapi_pass: "{{ splunk_common_admin_passwd }}"
    ansible_httpapi_port: "{{ kube_service_ports['svc-8089'] if (kube_service_ports is defined and kube_service_ports['svc-8089'] is defined) else ('8089') }}"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: False
    ansible_connection: httpapi

  tasks:
    - name: create splunk_data_input_network
      splunk.es.data_input_network:
        name: "9199"
        protocol: "tcp"
        source: "http:tower_logging_collections"
        sourcetype: "httpevent"
        state: "present"