- hosts: all
  become: yes
  vars:
    splunk_version:	8.0.3
    splunk_build: a6754d8441bf
    splunk_common_enable_ssl: True
    splunk_common_http_port: 8443
  tasks:
    - name: ensure required packages are installed (rhel == 7)
      yum:
        name: http://www.nosuchhost.net/~cheese/fedora/packages/epel-7/x86_64/python2-pyOpenSSL-16.2.0-4.el7.noarch.rpm
        state: present
      when: ansible_distribution_major_version|int == 7

    - name: ensure required packages are installed (rhel == 8)
      package:
        name: python3-pyOpenSSL
        state: present
      when: ansible_distribution_major_version|int == 8

    - name: import splunk gpg key
      rpm_key:
        state: present
        key: https://docs.splunk.com/images/6/6b/SplunkPGPKey.pub

    - include_role:
        name: ansible-splunk-common
        apply:
          become: yes

    - name: ensure splunk service is running
      service:
        name: splunk
        state: started